<div class="row, wide">
   <div class="col-md-4, white">
      <address>
         <a href="http://www.zib.de"><strong>Zuse Institute Berlin (ZIB)</strong></a><br>
         Takustra&szlig;e 7<br>
         14195 Berlin (Germany)<br>
      </address>
      <address>
         Phone:  +49 30 84185 245<br>
         e-Mail: miltenberger<img src="klammeraffe.gif" align="top" border="0" alt="at">zib.de<br>
      </address>
   </div>
   <!--<div class="col-md-4">
      <img class="picture" src="beoriginal-banner.png" alt="picture">
   </div>-->
   <div class="col-md-2, col-md-offset-10">
      <img class="picture" src="miltenberger.jpg" alt="picture">
   </div>
</div>
